version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max-allowed-packet=256M
      --max_connections=250
      --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pm3
      MYSQL_USER: pm3
      MYSQL_PASSWORD: notroot
    cap_add:
      - SYS_NICE
    volumes:
      #- "./dump/:/docker-entrypoint-initdb.d"
      - "./mysql_data/:/var/lib/mysql/"
    ports:
      - "3306:3306"
  web:
    command:
      [
        "/usr/bin/share/wait-for-it.sh",
        "--timeout=60",
        "db:3306",
        "--",
        "catalina.sh",
        "run",
      ]
    image: tomcat:7.0
    depends_on:
      - db
    volumes:
      - ./webapp/:/usr/local/tomcat/webapps/ROOT/
      - ./init_script/wait-for-it.sh:/usr/bin/share/wait-for-it.sh
    ports:
      - "8080:8080"
